#!/usr/bin/env bash
# Install the `alloy` command so it works after this script finishes.
# Safe on Linux and macOS. Never overwrites bin/alloy.mjs (the real launcher).
#
# Usage:
#   npm run install-cli
#   bash scripts/install-cli.sh
#   source scripts/install-cli.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_SRC="$ROOT/bin/alloy.mjs"
LOCAL_BIN="${ALLOY_BIN_DIR:-$HOME/.local/bin}"
ENV_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/alloy/env"

_SOURCED=0
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  _SOURCED=1
fi

log() { printf '%s\n' "$*"; }
err() { printf 'error: %s\n' "$*" >&2; }
shell_quote() {
  local value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

# --- resolve realpath (Linux + macOS) ----------------------------------------
_realpath() {
  if command -v realpath >/dev/null 2>&1; then
    realpath "$1" 2>/dev/null || realpath -m "$1" 2>/dev/null || echo "$1"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
  else
    # Fallback: cd + pwd for directories; for files use readlink -f if present
    if [[ -d "$1" ]]; then
      (cd "$1" && pwd -P)
    elif command -v readlink >/dev/null 2>&1; then
      readlink -f "$1" 2>/dev/null || echo "$1"
    else
      echo "$1"
    fi
  fi
}

if [[ ! -f "$BIN_SRC" ]]; then
  err "missing launcher at $BIN_SRC"
  exit 1
fi

# Detect accidental corruption (bash wrapper written over the JS source)
if ! head -1 "$BIN_SRC" | grep -q 'node\|javascript\|esm\|import\|/\*\|//'; then
  if head -5 "$BIN_SRC" | grep -q 'Generated by Alloy install-cli'; then
    err "bin/alloy.mjs was overwritten by a previous broken install (symlink follow)."
    err "Restore it, then re-run install:"
    err "  cd $ROOT && git checkout -- bin/alloy.mjs && npm run install-cli"
    exit 1
  fi
fi

# Must look like the Node launcher
if ! head -1 "$BIN_SRC" | grep -qE 'node|#!/'; then
  err "bin/alloy.mjs does not look like a Node script. Restore from git."
  exit 1
fi

TUI_ROOT="$ROOT/tui"
for resource in \
  "$TUI_ROOT/package.json" \
  "$TUI_ROOT/bun.lock" \
  "$TUI_ROOT/src/index.tsx"; do
  if [[ ! -f "$resource" ]]; then
    err "missing required TUI resource: $resource"
    exit 1
  fi
done

if ! command -v bun >/dev/null 2>&1; then
  err "Bun 1.3.14 is required. Install that exact version first."
  exit 1
fi
if [[ "$(bun --version 2>/dev/null || true)" != "1.3.14" ]]; then
  err "Bun 1.3.14 is required. Found: $(bun --version 2>/dev/null || printf unknown)"
  exit 1
fi
BUN_BIN="$(_realpath "$(command -v bun)")"

if ! command -v node >/dev/null 2>&1; then
  err "node not found on PATH. Install Node 22.19+ first."
  exit 1
fi
NODE_BIN="$(_realpath "$(command -v node)")"
NODE_VERSION="$("$NODE_BIN" -p 'process.versions.node' 2>/dev/null || true)"
if [[ ! "$NODE_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]] ||
  (( BASH_REMATCH[1] < 22 || (BASH_REMATCH[1] == 22 && BASH_REMATCH[2] < 19) )); then
  err "Node 22.19+ is required. Found: ${NODE_VERSION:-unknown}"
  exit 1
fi

NODE_BIN_DIR="$(cd "$(dirname "$NODE_BIN")" && pwd)"
NODE_BIN_DIR_REAL="$(_realpath "$NODE_BIN_DIR")"
NPM_EXECUTABLE="$NODE_BIN_DIR/npm"
if [[ ! -x "$NPM_EXECUTABLE" ]]; then
  command -v npm >/dev/null 2>&1 || {
    err "npm not found next to the recorded Node runtime or on PATH"
    exit 1
  }
  NPM_EXECUTABLE="$(_realpath "$(command -v npm)")"
fi

chmod +x "$BIN_SRC" 2>/dev/null || true
BIN_SRC_REAL="$(_realpath "$BIN_SRC")"

# --- dependencies ------------------------------------------------------------
if [[ ! -d "$ROOT/node_modules/@earendil-works/pi-coding-agent" ]]; then
  log "Installing npm dependencies in $ROOT …"
  (cd "$ROOT" && "$NPM_EXECUTABLE" ci)
fi

log "Installing frozen TUI dependencies in $TUI_ROOT …"
(cd "$TUI_ROOT" && "$BUN_BIN" install --frozen-lockfile </dev/null)

# --- write bash wrapper to dest (never through a symlink into BIN_SRC) -------
write_wrapper() {
  local dest="$1"
  local dest_dir
  dest_dir="$(dirname "$dest")"
  mkdir -p "$dest_dir"

  # If dest is a symlink, remove it first so we don't follow it and
  # clobber bin/alloy.mjs.
  if [[ -L "$dest" ]]; then
    log "Removing old symlink: $dest"
    rm -f "$dest"
  fi

  # Refuse to overwrite the JS source (direct path or same inode after resolve)
  if [[ "$dest" == "$BIN_SRC" || "$dest" == "$BIN_SRC_REAL" ]]; then
    err "refusing to overwrite source launcher: $dest"
    return 1
  fi
  if [[ -e "$dest" && ! -L "$dest" ]]; then
    local dest_real
    dest_real="$(_realpath "$dest")"
    if [[ "$dest_real" == "$BIN_SRC_REAL" ]]; then
      err "refusing to overwrite source launcher via $dest -> $dest_real"
      return 1
    fi
  fi

  # Write to a temp file then mv (atomic, never follows dest symlink we already removed)
  local tmp
  tmp="$(mktemp "${dest_dir}/.alloy-wrap.XXXXXX")"
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' '# Generated by Alloy install-cli.sh; do not edit.'
    printf '%s\n' 'set -euo pipefail'
    printf 'ROOT=%s\n' "$(shell_quote "$ROOT")"
    printf 'NODE_BIN=%s\n' "$(shell_quote "$NODE_BIN")"
    printf 'ALLOY_BUN_BIN=%s\n' "$(shell_quote "$BUN_BIN")"
    printf '%s\n' 'export ALLOY_BUN_BIN'
    printf '%s\n' 'BIN="$ROOT/bin/alloy.mjs"'
    printf '%s\n' 'NODE_VERSION="$("$NODE_BIN" -p '\''process.versions.node'\'' 2>/dev/null || true)"'
    printf '%s\n' 'if [[ ! "$NODE_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]] || (( BASH_REMATCH[1] < 22 || (BASH_REMATCH[1] == 22 && BASH_REMATCH[2] < 19) )); then'
    printf '%s\n' '  echo "Recorded Node runtime must be 22.19+; found: ${NODE_VERSION:-unknown}" >&2'
    printf '%s\n' '  exit 1'
    printf '%s\n' 'fi'
    printf '%s\n' 'if [[ "$("$ALLOY_BUN_BIN" --version 2>/dev/null || true)" != "1.3.14" ]]; then'
    printf '%s\n' '  echo "Recorded Bun runtime must be 1.3.14" >&2'
    printf '%s\n' '  exit 1'
    printf '%s\n' 'fi'
    printf '%s\n' 'if [[ ! -f "$BIN" ]]; then'
    printf '%s\n' '  echo "Alloy launcher missing: $BIN" >&2'
    printf '%s\n' '  exit 1'
    printf '%s\n' 'fi'
    printf '%s\n' 'if head -1 "$BIN" | grep -q '\''Generated by Alloy install-cli'\''; then'
    printf '%s\n' '  echo "Alloy source bin/alloy.mjs is corrupted (bash wrapper)." >&2'
    printf '%s\n' '  exit 1'
    printf '%s\n' 'fi'
    printf '%s\n' 'exec "$NODE_BIN" "$BIN" "$@"'
  } > "$tmp"
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"
}

INSTALLED=()

# 1) Next to node (usually already on PATH through a version manager)
NODE_ALLOY="$NODE_BIN_DIR/alloy"
if write_wrapper "$NODE_ALLOY"; then
  INSTALLED+=("$NODE_ALLOY")
  log "Installed: $NODE_ALLOY  (next to node)"
fi

# 2) ~/.local/bin (stable across node version switches)
mkdir -p "$LOCAL_BIN"
LOCAL_ALLOY="$LOCAL_BIN/alloy"
# Only install again if different path from node bin
if [[ "$(_realpath "$LOCAL_BIN")" != "$NODE_BIN_DIR_REAL" ]]; then
  if write_wrapper "$LOCAL_ALLOY"; then
    INSTALLED+=("$LOCAL_ALLOY")
    log "Installed: $LOCAL_ALLOY"
  fi
else
  log "Note: node bin is already $LOCAL_BIN (single install there)"
  INSTALLED+=("$LOCAL_ALLOY")
fi

# 3) npm global bin when writable and distinct
if command -v npm >/dev/null 2>&1; then
  NPM_PREFIX="$("$NPM_EXECUTABLE" prefix -g 2>/dev/null || true)"
  if [[ -n "${NPM_PREFIX:-}" ]]; then
    NPM_GLOBAL_BIN="$NPM_PREFIX/bin"
    NPM_GLOBAL_BIN_REAL="$(_realpath "$NPM_GLOBAL_BIN" 2>/dev/null || echo "$NPM_GLOBAL_BIN")"
    if [[ "$NPM_GLOBAL_BIN_REAL" != "$NODE_BIN_DIR_REAL" && "$NPM_GLOBAL_BIN_REAL" != "$(_realpath "$LOCAL_BIN")" ]]; then
      if mkdir -p "$NPM_GLOBAL_BIN" 2>/dev/null && [[ -w "$NPM_GLOBAL_BIN" ]]; then
        if write_wrapper "$NPM_GLOBAL_BIN/alloy"; then
          INSTALLED+=("$NPM_GLOBAL_BIN/alloy")
          log "Installed: $NPM_GLOBAL_BIN/alloy  (npm global bin)"
        fi
      fi
    fi
  fi
fi

# --- PATH / shell rc ---------------------------------------------------------
PATH_LINE="export PATH=$(shell_quote "$LOCAL_BIN"):\$PATH"

ensure_path_line() {
  local file="$1"
  [[ -z "$file" ]] && return 0
  if [[ ! -f "$file" ]]; then
    case "$file" in
      "$HOME/.bashrc"|"$HOME/.zshrc"|"$HOME/.profile"|"$HOME/.bash_profile")
        touch "$file"
        ;;
      *) return 0 ;;
    esac
  fi
  if grep -qF "$LOCAL_BIN" "$file" 2>/dev/null; then
    return 0
  fi
  {
    echo ""
    echo "# Alloy CLI — ensure ~/.local/bin is on PATH"
    echo "$PATH_LINE"
  } >> "$file"
  log "Updated PATH in $file"
}

ensure_path_line "$HOME/.bashrc"
ensure_path_line "$HOME/.zshrc"
ensure_path_line "$HOME/.profile"
[[ -f "$HOME/.bash_profile" ]] && ensure_path_line "$HOME/.bash_profile"

mkdir -p "$(dirname "$ENV_FILE")"
{
  printf '%s\n' '# Generated by Alloy install-cli.sh'
  printf 'export PATH=%s:$PATH\n' "$(shell_quote "$LOCAL_BIN")"
  printf '%s\n' 'hash -r 2>/dev/null || true'
} > "$ENV_FILE"
log "Wrote $ENV_FILE"

export PATH="$LOCAL_BIN:$NODE_BIN_DIR:${PATH:-}"
hash -r 2>/dev/null || true

# --- verify ------------------------------------------------------------------
# Prefer a path that is on PATH
ALLOY_PATH="$(command -v alloy 2>/dev/null || true)"
if [[ -z "$ALLOY_PATH" ]]; then
  for c in "${INSTALLED[@]}"; do
    if [[ -x "$c" ]]; then
      ALLOY_PATH="$c"
      break
    fi
  done
fi

if [[ -z "${ALLOY_PATH:-}" || ! -x "$ALLOY_PATH" ]]; then
  err "alloy still not found after install."
  err "Tried: ${INSTALLED[*]:-none}"
  exit 1
fi

log ""
log "OK — alloy is installed at: $ALLOY_PATH"

# Smoke: must invoke the bash wrapper OR node on real JS — not corrupted source
if ! "$ALLOY_PATH" --help >/dev/null 2>&1; then
  log "Warning: alloy --help failed."
  log "  cd $ROOT && npm ci && npm run install-cli"
  # Show a few lines of error for debugging
  "$ALLOY_PATH" --help 2>&1 | head -20 || true
else
  log "Smoke check: alloy --help succeeded"
fi

log ""
log "Done. Try:"
log "  alloy"
log ""
if [[ "$_SOURCED" -eq 1 ]]; then
  log "(sourced — PATH updated in this shell)"
  return 0 2>/dev/null || true
fi
