#!/usr/bin/env bash
# Install the `alloy` command so it works in THIS shell and future shells.
#
# Usage:
#   npm run install-cli
#   bash scripts/install-cli.sh
#   source scripts/install-cli.sh   # also exports PATH in the current shell
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_SRC="$ROOT/bin/alloy.mjs"
LOCAL_BIN="${ALLOY_BIN_DIR:-$HOME/.local/bin}"
ENV_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/alloy/env"

# Are we being sourced? (so we can export PATH into the caller's shell)
_SOURCED=0
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  _SOURCED=1
elif [[ -n "${ZSH_EVAL_CONTEXT:-}" && "$ZSH_EVAL_CONTEXT" == *:file* ]]; then
  _SOURCED=1
fi

log() { printf '%s\n' "$*"; }
err() { printf 'error: %s\n' "$*" >&2; }

if [[ ! -f "$BIN_SRC" ]]; then
  err "missing launcher at $BIN_SRC"
  exit 1
fi
chmod +x "$BIN_SRC"

# --- dependencies -----------------------------------------------------------
if [[ ! -d "$ROOT/node_modules/@earendil-works/pi-coding-agent" ]]; then
  log "Installing npm dependencies in $ROOT …"
  (cd "$ROOT" && npm install)
fi

# Resolve node (required)
if ! command -v node >/dev/null 2>&1; then
  err "node not found on PATH. Install Node 20+ first (nvm, apt, etc.)."
  exit 1
fi
NODE_BIN_DIR="$(cd "$(dirname "$(command -v node)")" && pwd)"

# --- write launcher wrapper -------------------------------------------------
# Wrapper always points at this checkout's bin/alloy.mjs via absolute path.
write_wrapper() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"
  cat > "$dest" <<EOF
#!/usr/bin/env bash
# Generated by Alloy install-cli.sh — do not edit.
set -euo pipefail
ROOT="$ROOT"
BIN="\$ROOT/bin/alloy.mjs"
if [[ ! -f "\$BIN" ]]; then
  echo "Alloy launcher missing: \$BIN" >&2
  echo "Re-run: cd $ROOT && npm run install-cli" >&2
  exit 1
fi
# Prefer node from PATH; fall back to the node used at install time.
if command -v node >/dev/null 2>&1; then
  exec node "\$BIN" "\$@"
else
  exec "$NODE_BIN_DIR/node" "\$BIN" "\$@"
fi
EOF
  chmod +x "$dest"
}

# --- install locations ------------------------------------------------------
# 1) Next to node (almost always already on PATH → works immediately)
# 2) ~/.local/bin (stable across nvm version switches, if on PATH)
INSTALLED=()

NODE_ALLOY="$NODE_BIN_DIR/alloy"
write_wrapper "$NODE_ALLOY"
INSTALLED+=("$NODE_ALLOY")
log "Installed: $NODE_ALLOY  (next to node — usually already on PATH)"

mkdir -p "$LOCAL_BIN"
LOCAL_ALLOY="$LOCAL_BIN/alloy"
write_wrapper "$LOCAL_ALLOY"
INSTALLED+=("$LOCAL_ALLOY")
log "Installed: $LOCAL_ALLOY"

# 3) npm global prefix/bin when available and writable
if command -v npm >/dev/null 2>&1; then
  NPM_PREFIX="$(npm prefix -g 2>/dev/null || true)"
  if [[ -n "${NPM_PREFIX:-}" && -d "$NPM_PREFIX" ]]; then
    NPM_BIN="$NPM_PREFIX/bin"
    if [[ -w "$NPM_PREFIX" ]] || [[ -w "$NPM_BIN" ]] || mkdir -p "$NPM_BIN" 2>/dev/null; then
      if [[ -w "$NPM_BIN" ]] || [[ -w "$NPM_PREFIX" ]]; then
        write_wrapper "$NPM_BIN/alloy"
        INSTALLED+=("$NPM_BIN/alloy")
        log "Installed: $NPM_BIN/alloy  (npm global bin)"
      fi
    fi
  fi
fi

# --- PATH / shell rc --------------------------------------------------------
PATH_LINE="export PATH=\"$LOCAL_BIN:\$PATH\""

ensure_path_line() {
  local file="$1"
  [[ -z "$file" ]] && return 0
  # Create file if it's a standard rc we care about and parent exists
  if [[ ! -f "$file" ]]; then
    case "$file" in
      "$HOME/.bashrc"|"$HOME/.zshrc"|"$HOME/.profile")
        touch "$file"
        ;;
      *)
        return 0
        ;;
    esac
  fi
  if grep -qF "$LOCAL_BIN" "$file" 2>/dev/null; then
    return 0
  fi
  {
    echo ""
    echo "# Alloy CLI — ensure ~/.local/bin is on PATH"
    echo "$PATH_LINE"
  } >> "$file"
  log "Updated PATH in $file"
}

ensure_path_line "$HOME/.bashrc"
ensure_path_line "$HOME/.zshrc"
ensure_path_line "$HOME/.profile"
# Debian/Ubuntu often uses .bash_profile or .profile for login shells
[[ -f "$HOME/.bash_profile" ]] && ensure_path_line "$HOME/.bash_profile"

# Env file for: source ~/.local/share/alloy/env
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by Alloy install-cli.sh
export PATH="$LOCAL_BIN:\$PATH"
hash -r 2>/dev/null || true
EOF
log "Wrote $ENV_FILE"

# Export into current process (works when sourced; also helps verification below)
export PATH="$LOCAL_BIN:$NODE_BIN_DIR:${PATH:-}"
hash -r 2>/dev/null || true

# --- verify -----------------------------------------------------------------
ALLOY_PATH="$(command -v alloy 2>/dev/null || true)"
if [[ -z "$ALLOY_PATH" ]]; then
  # Force-hash specific installs
  for c in "${INSTALLED[@]}"; do
    if [[ -x "$c" ]]; then
      ALLOY_PATH="$c"
      break
    fi
  done
fi

if [[ -n "$ALLOY_PATH" && -x "$ALLOY_PATH" ]]; then
  log ""
  log "OK — alloy is installed at: $ALLOY_PATH"
  # Smoke: resolve Pi without starting full TUI
  if ! "$ALLOY_PATH" --help >/dev/null 2>&1; then
    log "Warning: alloy --help failed; try: cd $ROOT && npm install"
  else
    log "Smoke check: alloy --help succeeded"
  fi
else
  err "alloy still not found after install."
  err "Tried: ${INSTALLED[*]}"
  exit 1
fi

log ""
log "Done. In this terminal, try:"
log "  alloy"
log ""
if [[ "$_SOURCED" -eq 1 ]]; then
  log "(script was sourced — PATH is updated in this shell)"
  # shellcheck disable=SC1090
  # PATH already exported above
else
  # Parent shell (e.g. after npm run) may not see PATH changes if node-bin
  # wasn't already on PATH. Node-bin install usually fixes that.
  if ! command -v alloy >/dev/null 2>&1; then
    log "If a new prompt still says 'alloy: not found', run:"
    log "  source $ENV_FILE"
    log "  # or open a new terminal"
  fi
fi

# When sourced, don't exit with failure codes from set -e edge cases
if [[ "$_SOURCED" -eq 1 ]]; then
  return 0 2>/dev/null || true
fi
