#!/usr/bin/env bash
# Install the `alloy` command so it works after this script finishes.
# Safe on Linux and macOS. Never overwrites bin/alloy.mjs (the real launcher).
#
# Usage:
#   npm run install-cli
#   bash scripts/install-cli.sh
#   source scripts/install-cli.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_SRC="$ROOT/bin/alloy.mjs"
LOCAL_BIN="${ALLOY_BIN_DIR:-$HOME/.local/bin}"
ENV_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/alloy/env"

_SOURCED=0
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  _SOURCED=1
fi

log() { printf '%s\n' "$*"; }
err() { printf 'error: %s\n' "$*" >&2; }

# --- resolve realpath (Linux + macOS) ----------------------------------------
_realpath() {
  if command -v realpath >/dev/null 2>&1; then
    realpath "$1" 2>/dev/null || realpath -m "$1" 2>/dev/null || echo "$1"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
  else
    # Fallback: cd + pwd for directories; for files use readlink -f if present
    if [[ -d "$1" ]]; then
      (cd "$1" && pwd -P)
    elif command -v readlink >/dev/null 2>&1; then
      readlink -f "$1" 2>/dev/null || echo "$1"
    else
      echo "$1"
    fi
  fi
}

if [[ ! -f "$BIN_SRC" ]]; then
  err "missing launcher at $BIN_SRC"
  exit 1
fi

# Detect accidental corruption (bash wrapper written over the JS source)
if ! head -1 "$BIN_SRC" | grep -q 'node\|javascript\|esm\|import\|/\*\|//'; then
  if head -5 "$BIN_SRC" | grep -q 'Generated by Alloy install-cli'; then
    err "bin/alloy.mjs was overwritten by a previous broken install (symlink follow)."
    err "Restore it, then re-run install:"
    err "  cd $ROOT && git checkout -- bin/alloy.mjs && npm run install-cli"
    exit 1
  fi
fi

# Must look like the Node launcher
if ! head -1 "$BIN_SRC" | grep -qE 'node|#!/'; then
  err "bin/alloy.mjs does not look like a Node script. Restore from git."
  exit 1
fi

chmod +x "$BIN_SRC" 2>/dev/null || true
BIN_SRC_REAL="$(_realpath "$BIN_SRC")"

# --- dependencies ------------------------------------------------------------
if [[ ! -d "$ROOT/node_modules/@earendil-works/pi-coding-agent" ]]; then
  log "Installing npm dependencies in $ROOT …"
  (cd "$ROOT" && npm ci)
fi

if ! command -v node >/dev/null 2>&1; then
  err "node not found on PATH. Install Node 22.19+ first."
  exit 1
fi
NODE_BIN_DIR="$(cd "$(dirname "$(command -v node)")" && pwd)"
NODE_BIN_DIR_REAL="$(_realpath "$NODE_BIN_DIR")"

# --- write bash wrapper to dest (never through a symlink into BIN_SRC) -------
write_wrapper() {
  local dest="$1"
  local dest_dir
  dest_dir="$(dirname "$dest")"
  mkdir -p "$dest_dir"

  # If dest is a symlink, remove it first so we don't follow it and
  # clobber bin/alloy.mjs.
  if [[ -L "$dest" ]]; then
    log "Removing old symlink: $dest"
    rm -f "$dest"
  fi

  # Refuse to overwrite the JS source (direct path or same inode after resolve)
  if [[ "$dest" == "$BIN_SRC" || "$dest" == "$BIN_SRC_REAL" ]]; then
    err "refusing to overwrite source launcher: $dest"
    return 1
  fi
  if [[ -e "$dest" && ! -L "$dest" ]]; then
    local dest_real
    dest_real="$(_realpath "$dest")"
    if [[ "$dest_real" == "$BIN_SRC_REAL" ]]; then
      err "refusing to overwrite source launcher via $dest -> $dest_real"
      return 1
    fi
  fi

  # Write to a temp file then mv (atomic, never follows dest symlink we already removed)
  local tmp
  tmp="$(mktemp "${dest_dir}/.alloy-wrap.XXXXXX")"
  cat > "$tmp" <<EOF
#!/usr/bin/env bash
# Generated by Alloy install-cli.sh — do not edit.
set -euo pipefail
ROOT="$ROOT"
BIN="\$ROOT/bin/alloy.mjs"
if [[ ! -f "\$BIN" ]]; then
  echo "Alloy launcher missing: \$BIN" >&2
  echo "Re-run: cd $ROOT && git checkout -- bin/alloy.mjs && npm run install-cli" >&2
  exit 1
fi
# Guard: source must be JavaScript, not a nested bash wrapper
if head -1 "\$BIN" | grep -q 'Generated by Alloy install-cli'; then
  echo "Alloy source bin/alloy.mjs is corrupted (bash wrapper). Restore:" >&2
  echo "  cd $ROOT && git checkout -- bin/alloy.mjs && npm run install-cli" >&2
  exit 1
fi
if command -v node >/dev/null 2>&1; then
  exec node "\$BIN" "\$@"
else
  exec "$NODE_BIN_DIR/node" "\$BIN" "\$@"
fi
EOF
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"
}

INSTALLED=()

# 1) Next to node (usually already on PATH through a version manager)
NODE_ALLOY="$NODE_BIN_DIR/alloy"
if write_wrapper "$NODE_ALLOY"; then
  INSTALLED+=("$NODE_ALLOY")
  log "Installed: $NODE_ALLOY  (next to node)"
fi

# 2) ~/.local/bin (stable across node version switches)
mkdir -p "$LOCAL_BIN"
LOCAL_ALLOY="$LOCAL_BIN/alloy"
# Only install again if different path from node bin
if [[ "$(_realpath "$LOCAL_BIN")" != "$NODE_BIN_DIR_REAL" ]]; then
  if write_wrapper "$LOCAL_ALLOY"; then
    INSTALLED+=("$LOCAL_ALLOY")
    log "Installed: $LOCAL_ALLOY"
  fi
else
  log "Note: node bin is already $LOCAL_BIN (single install there)"
  INSTALLED+=("$LOCAL_ALLOY")
fi

# 3) npm global bin when writable and distinct
if command -v npm >/dev/null 2>&1; then
  NPM_PREFIX="$(npm prefix -g 2>/dev/null || true)"
  if [[ -n "${NPM_PREFIX:-}" ]]; then
    NPM_BIN="$NPM_PREFIX/bin"
    NPM_BIN_REAL="$(_realpath "$NPM_BIN" 2>/dev/null || echo "$NPM_BIN")"
    if [[ "$NPM_BIN_REAL" != "$NODE_BIN_DIR_REAL" && "$NPM_BIN_REAL" != "$(_realpath "$LOCAL_BIN")" ]]; then
      if mkdir -p "$NPM_BIN" 2>/dev/null && [[ -w "$NPM_BIN" ]]; then
        if write_wrapper "$NPM_BIN/alloy"; then
          INSTALLED+=("$NPM_BIN/alloy")
          log "Installed: $NPM_BIN/alloy  (npm global bin)"
        fi
      fi
    fi
  fi
fi

# --- PATH / shell rc ---------------------------------------------------------
PATH_LINE="export PATH=\"$LOCAL_BIN:\$PATH\""

ensure_path_line() {
  local file="$1"
  [[ -z "$file" ]] && return 0
  if [[ ! -f "$file" ]]; then
    case "$file" in
      "$HOME/.bashrc"|"$HOME/.zshrc"|"$HOME/.profile"|"$HOME/.bash_profile")
        touch "$file"
        ;;
      *) return 0 ;;
    esac
  fi
  if grep -qF "$LOCAL_BIN" "$file" 2>/dev/null; then
    return 0
  fi
  {
    echo ""
    echo "# Alloy CLI — ensure ~/.local/bin is on PATH"
    echo "$PATH_LINE"
  } >> "$file"
  log "Updated PATH in $file"
}

ensure_path_line "$HOME/.bashrc"
ensure_path_line "$HOME/.zshrc"
ensure_path_line "$HOME/.profile"
[[ -f "$HOME/.bash_profile" ]] && ensure_path_line "$HOME/.bash_profile"

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by Alloy install-cli.sh
export PATH="$LOCAL_BIN:\$PATH"
hash -r 2>/dev/null || true
EOF
log "Wrote $ENV_FILE"

export PATH="$LOCAL_BIN:$NODE_BIN_DIR:${PATH:-}"
hash -r 2>/dev/null || true

# --- verify ------------------------------------------------------------------
# Prefer a path that is on PATH
ALLOY_PATH="$(command -v alloy 2>/dev/null || true)"
if [[ -z "$ALLOY_PATH" ]]; then
  for c in "${INSTALLED[@]}"; do
    if [[ -x "$c" ]]; then
      ALLOY_PATH="$c"
      break
    fi
  done
fi

if [[ -z "${ALLOY_PATH:-}" || ! -x "$ALLOY_PATH" ]]; then
  err "alloy still not found after install."
  err "Tried: ${INSTALLED[*]:-none}"
  exit 1
fi

log ""
log "OK — alloy is installed at: $ALLOY_PATH"

# Smoke: must invoke the bash wrapper OR node on real JS — not corrupted source
if ! "$ALLOY_PATH" --help >/dev/null 2>&1; then
  log "Warning: alloy --help failed."
  log "  cd $ROOT && npm ci && npm run install-cli"
  # Show a few lines of error for debugging
  "$ALLOY_PATH" --help 2>&1 | head -20 || true
else
  log "Smoke check: alloy --help succeeded"
fi

log ""
log "Done. Try:"
log "  alloy"
log ""
if [[ "$_SOURCED" -eq 1 ]]; then
  log "(sourced — PATH updated in this shell)"
  return 0 2>/dev/null || true
fi
